source/calculation/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from calculation import views

urlpatterns = [
    url(r'^$', views.input_page, name='calc_home'),
    url(r'^(?P<calc_name>.*)/input/$', views.input_page, name='calc_ipage'),
    url(r'^result/(?P<pk>[0-9]+)/$', views.result_page, name='calc_rpage'),
]

source/calman/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""moc URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import global_settings

from calculation import urls as cproc_urls
from study import urls as study_urls
from reports import urls as reports_urls
from website import urls as website_urls


urlpatterns = [
    url(r'^', include(website_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^calculation/', include(cproc_urls)),
    url(r'^study/', include(study_urls)),
    url(r'^reports/', include(reports_urls)),
]

if global_settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(url(r'^__debug__/', include(debug_toolbar.urls)))

source/study/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from study import views

urlpatterns = [
    url(r'^$', views.input_page, name='study_home'),
    url(r'^(?P<study_name>.*)/input/$', views.input_page, name='study_ipage'),
    url(r'^result/(?P<pk>[0-9]+)/$', views.result_page, name='study_rpage'),
]

source/calculation/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import jsonfield
import ast

from django.db import models
from django.utils.translation import ugettext as _
from django.utils import timezone


class ListField(models.TextField):
    """List Field for django of basic object."""
    __metaclass__ = models.SubfieldBase
    description = "Stores a python list of basic object"

    def from_db_value(self, value, expression, connection, context):
        if value is None:
            return value
        return ast.literal_eval(value)

    def to_python(self, value):
        if isinstance(value, list):
            return value

        if value is None:
            return value

        return ast.literal_eval(value)

    def get_prep_value(self, value):
        if value is None:
            return value

        return str(value)


class Solver(models.Model):
    """Solver for a calculation."""

    # Block needed for named fixtures (not only pk in fixture)
    # --------------------------------------------------------
    class SolverManager(models.Manager):

        def get_by_natural_key(self, name):
            return self.get(name=name)

    objects = SolverManager()

    def natural_key(self):
        return (self.name,)
    # --------------------------------------------------------

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Mesher(models.Model):
    """Mesher for a calculation with an EF solver."""

    # Block needed for named fixtures (not only pk in fixture)
    # --------------------------------------------------------
    class MesherManager(models.Manager):

        def get_by_natural_key(self, name):
            return self.get(name=name)

    objects = MesherManager()

    def natural_key(self):
        return (self.name,)
    # --------------------------------------------------------

    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Tags(models.Model):
    """Tags for a calculation."""

    # Block needed for named fixtures (not only pk in fixture)
    # --------------------------------------------------------
    class TagsManager(models.Manager):

        def get_by_natural_key(self, name):
            return self.get(name=name)

    objects = TagsManager()

    def natural_key(self):
        return (self.name,)
    # --------------------------------------------------------

    name = models.CharField(max_length=50,
                            unique=True)

    def __str__(self):
        return self.name


class CalculationCategory(models.Model):
    """Category for a calculation."""

    # Block needed for named fixtures (not only pk in fixture)
    # --------------------------------------------------------
    class CalculationCategoryManager(models.Manager):

        def get_by_natural_key(self, title):
            return self.get(title=title)

    objects = CalculationCategoryManager()

    def natural_key(self):
        return (self.title,)
    # --------------------------------------------------------

    title = models.CharField(_('title'), max_length=250, unique=True)
    parent = models.ForeignKey('self', blank=True, null=True, related_name='child',
                               on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Calculation's categories"
        ordering = ['title']

    def __str__(self):
        p_list = self._recurse_for_parents(self)
        p_list.append(self.title)
        return self.get_separator().join(p_list)

    def _recurse_for_parents(self, cat_obj):
        p_list = []
        if cat_obj.parent_id:
            p = cat_obj.parent
            p_list.append(p.title)
            more = self._recurse_for_parents(p)
            p_list.extend(more)
        if cat_obj == self and p_list:
            p_list.reverse()
        return p_list

    def get_separator(self):
        return ' :: '


class CalculationDefinition(models.Model):
    """Definition of a calculation."""

    # Block needed for named fixtures (not only pk in fixture)
    # --------------------------------------------------------
    class CalculationDefinitionManager(models.Manager):

        def get_by_natural_key(self, name):
            return self.get(name=name)

    objects = CalculationDefinitionManager()

    def natural_key(self):
        return (self.name,)
    # --------------------------------------------------------

    name = models.CharField(max_length=50, unique=True)
    category = models.ForeignKey(CalculationCategory)
    solvers = models.ManyToManyField(Solver)
    meshers = models.ManyToManyField(Mesher)
    description = models.TextField()
    hypothesis = ListField()
    images = jsonfield.JSONField(default=None)
    reports = jsonfield.JSONField(default=None)

    tags = models.ManyToManyField(Tags)

    ivars = jsonfield.JSONField(default=None)
    ovars = jsonfield.JSONField(default=None)

    def __str__(self):
        return self.name


class Calculation(models.Model):
    """A calculation with it's input and results."""
    name = models.CharField(max_length=50)
    definition = models.ForeignKey(CalculationDefinition)
    solver = models.ForeignKey(Solver)
    mesher = models.ForeignKey(Mesher, null=True, blank=True)

    created_date = models.DateTimeField(default=timezone.now)
    updated_date = models.DateTimeField(auto_now=True)
    cpu_time = models.DurationField(null=True, blank=True)

    ivars = jsonfield.JSONField()
    ovars = jsonfield.JSONField(default=None)

source/calculation/forms.py
#!/usr/bin/env python
# coding=utf-8


from django import forms
from django.utils.translation import ugettext as _

from calculation.models import Calculation
from calculation.fields import build_input_field, build_output_field

# Constants:
CONST = {
    "name": {
        "empty_error": _("Veuillez fournir un nom pour le calcul"),
        "placeholder": "",
        "css_class": "form-control",
        "pattern": "^[_A-z0-9]{1,}$",
    },
    "solver": {
        "empty_error": _("Veuillez choisir un solveur"),
        "css_class": "form-control c-select",
    },
    "mesher": {
        "empty_error": _("Veuillez choisir un mailleur"),
        "css_class": "form-control c-select",
    },
    "section": {
        "empty_error": _("Veuillez choisir une section"),
        "css_class": "form-control c-select",
    },
    "material": {
        "empty_error": _("Veuillez choisir un matériau"),
        "css_class": "form-control c-select",
    },
}


class CalculationForm(forms.ModelForm):

    class Meta:
        model = Calculation
        fields = ('name', 'solver', 'mesher')
        widgets = {
            # 'name': forms.fields.TextInput(attrs={
            #     'class': 'form-control',
            # }),
            'solver': forms.fields.Select(attrs={
                'class': 'form-control',
            }),
            'mesher': forms.fields.Select(attrs={
                'class': 'form-control',
            }),
        }

    def __init__(self, *args, **kwargs):

        # extraction des arguments supplémentaires fournis
        if 'ivars' in kwargs.keys():
            ivars = kwargs.pop('ivars')
        elif 'ovars' in kwargs.keys():
            ovars = kwargs.pop('ovars')
            ovars_result = kwargs.pop('ovars_result')
        if 'exclude_fields' in kwargs.keys():
            exclude_fields = kwargs.pop('exclude_fields')
        super(CalculationForm, self).__init__(*args, **kwargs)

        # Parametres de base
        if 'exclude_fields' in vars():
            if not 'name' in exclude_fields:
                self.fields['name'].widget.attrs["class"] = 'form-control'
        else:
            self.fields['name'].widget.attrs["class"] = 'form-control'

        if 'exclude_fields' in vars():
            if not 'solver' in exclude_fields:
                self.fields['solver'].widget.attrs["class"] = 'form-control'
        else:
            self.fields['solver'].widget.attrs["class"] = 'form-control'

        if 'exclude_fields' in vars():
            if not 'mesher' in exclude_fields:
                self.fields['mesher'].widget.attrs["class"] = 'form-control'
        else:
            self.fields['mesher'].widget.attrs["class"] = 'form-control'

        if 'ivars' in vars():
            for name, field_info in ivars.items():
                if 'exclude_fields' in vars():
                    if not name in exclude_fields:
                        self.fields['ivar_%s' % name] = build_input_field(name, field_info)
                else:
                    self.fields['ivar_%s' % name] = build_input_field(name, field_info)
        elif 'ovars' in vars():
            for name, field_info in ovars.items():
                if 'exclude_fields' in vars():
                    if not name in exclude_fields:
                        result = ovars_result[name]
                        self.fields['ovar_%s' % name] = build_output_field(name, field_info, result)
                else:
                    result = ovars_result[name]
                    self.fields['ovar_%s' % name] = build_output_field(name, field_info, result)

source/calculation/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.shortcuts import redirect, render, get_object_or_404
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.conf import settings

from calculation.models import CalculationDefinition, Calculation
from calculation.forms import CalculationForm
from solvers import run

import logging
logger = logging.getLogger(__name__)


def _calc_context(calculation_def):
    context = {
        "title": calculation_def.name.replace("_", " ").capitalize(),

        "activeMenuItem": "Calcul",
        "tags": calculation_def.tags.all(),
        "calc": calculation_def,
        "paths": (
            ("Calculation", reverse('calc_home')),
        ),
    }
    return context


def make_calculation_groups(calculation_def, form):
    groups = {'ungrouped': []}
    ParametersExist = False
    for field in form:
        if "ivar_" in field.name:
            ivar_name = field.name.replace('ivar_', '')
            ivar = calculation_def.ivars[ivar_name]
            if 'group' in ivar.keys():
                group = ivar['group']
                if not group in groups.keys():
                    groups[group] = [field]
                else:
                    groups[group].append(field)
            else:
                groups['ungrouped'].append(field)
            ParametersExist = True
    return groups, ParametersExist


def _input_context(calculation_def, form):
    """Function returning global context for the calculation."""

    # Recuperation des booleens
    thereIsNumber = False
    thereIsTorsor = False
    for value in calculation_def.ivars.values():
        if 'integer' == value['type'] or 'float' == value['type']:
            thereIsNumber = True
        if 'torsor' == value['type']:
            thereIsTorsor = True

    form.fields['name'].initial = 'default_name'

    solvers = calculation_def.solvers.all()
    if len(solvers) == 1:
        form.fields['solver'].initial = solvers[0]
    form.fields['solver'].queryset = solvers

    meshers = calculation_def.meshers.all()
    if len(meshers) > 0:
        thereIsMesher = True
        form.fields['mesher'].queryset = meshers
    else:
        thereIsMesher = False
    if len(meshers) == 1:
        form.fields['mesher'].initial = meshers[0]
    form.fields['mesher'].queryset = meshers

    groups, ParametersExist = make_calculation_groups(calculation_def, form)

    context = {
        "thereIsNumber": thereIsNumber,
        "thereIsTorsor": thereIsTorsor,
        "thereIsMesher": thereIsMesher,
        "groups": groups,
        "ParametersExist": ParametersExist,
    }

    context.update({'form': form})

    return context

def _render_image(FV_voile="19327 N", FH_voile="142 N", FV_jambe="982 N", FH_jambe="123 N"):
    from PIL import Image, ImageDraw, ImageFont
    path = settings.STATIC_ROOT + "/ferme.png"
    im = Image.open(path)
    draw = ImageDraw.Draw(im)
    draw.text((10,10), "Bonjour")
    del draw
    # write to stdout
    im.save(sys.stdout, "PNG")

def _result_context(calculation, form):
    """Function returning global context for the calculation."""

    calculation_def = calculation.definition

    # Recuperation des booleens
    thereIsNumber = False
    thereIsTorsor = False
    for value in calculation_def.ovars.values():
        if 'integer' == value['type'] or 'float' == value['type']:
            thereIsNumber = True
        if 'torsor' == value['type']:
            thereIsTorsor = True

    if calculation.mesher:
        thereIsMesher = True
    else:
        thereIsMesher = False

    context = {
        "thereIsNumber": thereIsNumber,
        "thereIsTorsor": thereIsTorsor,
        "thereIsMesher": thereIsMesher,
    }

    onumbers = {}
    otorsors = {}
    for field, value in calculation.definition.ovars.items():
        if 'float' in value['type'] or 'integer' in value['type']:
            onumbers[field] = calculation.ovars[field]
        elif 'torsor' in value['type']:
            otorsors[field] = calculation.ovars[field]

    context.update({'resu': calculation, 'onumbers': onumbers,
                    'otorsors': otorsors, 'form': form,
                    # "pdflatex": reverse('latex2pdf', kwargs={'pk': calculation.pk, 'resu_type': 'Calculation'})
                    })

    return context


def extract_ivars(cleaned_data):
    """Get input variables from cleaned data of the form."""

    # Delete keys which is not an input variable
    cleaned_data.pop('name')
    cleaned_data.pop('solver')
    cleaned_data.pop('mesher')

    # Get all input variables and clean their name
    ivars = {}
    for key, value in cleaned_data.items():
        if 'ivar_' in key:
            ivars[key.replace('ivar_', '')] = value

    return ivars


def get_calculation_or_run(calculation):
    logger.debug("inputs variables for calculation are : %s" % calculation.ivars)
    matches = Calculation.objects.filter(ivars=calculation.ivars)
    if matches:
        logger.info("Aucun calcul nécessaire, 'Calculation' avec les mêmes paramètres déjà existant !")
        calculation = matches[0]
    else:
        logger.info("Lancement de l'exécution du calcul : %s" % calculation)
        calculation.save()    # Sauvegarde préliminaire afin d'avoir un ID avant l'execution
        calculation.ovars, calculation.cpu_time = run.run(calculation)
        calculation.save()
    logger.debug("outputs variables for calculation are : %s" % calculation.ovars)
    return calculation


def input_page(request, calc_name=None):
    """Render input page."""
    calculation_def = get_object_or_404(CalculationDefinition, name=calc_name)

    form = CalculationForm(request.POST or None, ivars=calculation_def.ivars)
    if form.is_valid():
        fcalc = form.save(commit=False)
        fcalc.definition = calculation_def
        fcalc.ivars = extract_ivars(form.cleaned_data)
        fcalc = get_calculation_or_run(fcalc)
        return redirect('calc_rpage', pk=fcalc.pk)

    context = _calc_context(calculation_def)
    context.update(_input_context(calculation_def, form))

    return render(request, 'calculation_input_page.html', context)


def result_page(request, pk):
    """Render input page."""
    calculation = get_object_or_404(Calculation, pk=pk)

    form = CalculationForm(ovars=calculation.definition.ovars, ovars_result=calculation.ovars)

    context = _calc_context(calculation.definition)
    context.update(_result_context(calculation, form))

    return render(request, 'calculation_result_page.html', context)

source/calculation/templates/calculation_field.html
{# with field #}

<div class="form-group col-md-6">
  <span class="text-info">{{ field.field.description }}</span>
  <div class="input-group has-feedback {% if field.errors %}has-error{% elif request.method == 'POST' %}has-success{% endif %}" id="{{field.name}}">
    {{ field }}
  </div>
  {{ field.errors }}
</div>

source/calculation/templates/calculation_image.html
{# with calc category group #}
{% load staticfiles %}

{% if category == "description" %}
  {% for image in calc.images.description %}
    <div class="col-md-12">
      <div class="blog-post image-post">
        <!-- Post Thumb -->
        <div class="post-head">
          <a class="lightbox" title="{{category}}" href="{% static '/static/images/calculation/' %}/{{calc.name}}/{{image}}">
            <div class="thumb-overlay"><i class="fa fa-arrows-alt"></i></div>
            <img alt="" src="{% static '/static/images/calculation/' %}/{{calc.name}}/{{image}}">
          </a>
        </div>
      </div>
    </div>
    </br>
  {% endfor %}
{% elif category == "hypothesis" %}
  {% for image in calc.images.hypothesis %}
    <div class="col-md-6">
      <div class="blog-post image-post">
        <!-- Post Thumb -->
        <div class="post-head">
          <a class="lightbox" title="{{category}}" href="{% static '/static/images/calculation/' %}/{{calc.name}}/{{image}}">
            <div class="thumb-overlay"><i class="fa fa-arrows-alt"></i></div>
            <img alt="" src="{% static '/static/images/calculation/' %}/{{calc.name}}/{{image}}">
          </a>
        </div>
      </div>
    </div>
    </br>
  {% endfor %}
{% elif category == "parameters" %}
  {% for image in calc.images.parameters %}
    <div class="col-md-6">
      <div class="blog-post image-post">
        <!-- Post Thumb -->
        <div class="post-head">
          <a class="lightbox" title="{{category}}" href="{% static '/static/images/calculation/' %}/{{calc.name}}/{{image}}">
            <div class="thumb-overlay"><i class="fa fa-arrows-alt"></i></div>
            <img alt="" src="{% static '/static/images/calculation/' %}{{calc.name}}/{{image}}">
          </a>
        </div>
      </div>
    </div>
    </br>
  {% endfor %}
{% elif category == "group" %}
  {% for key, images in calc.images.group.items %}
    {% if group == key %}
      {% for image in images %}

        <div class="col-md-6">
          <div class="blog-post image-post">
            <!-- Post Thumb -->
            <div class="post-head">
              <a class="lightbox" title="{{category}}" href="{% static '/static/images/calculation/' %}/{{calc.name}}/{{image}}">
                <div class="thumb-overlay"><i class="fa fa-arrows-alt"></i></div>
                <img alt="" src="{% static '/static/images/calculation/' %}{{calc.name}}/{{image}}">
              </a>
            </div>
          </div>
        </div>
        </br>

      {% endfor %}
    {% endif %}
  {% endfor %}
{% endif %}

source/calculation/templates/calculation_input_content.html
{# --------------------- #}
{# Description du calcul #}
{# --------------------- #}
<h2 class="classic-title col-md-12"><span>Description</span></h2>
<p>{{ calc.description }}</p>
{% include "calculation_image.html" with calc=calc category="description" %}
</br>

{# -------------------- #}
{# Hypothèses du calcul #}
{# -------------------- #}
{% if calc.hypothesis %}
  <h2 class="classic-title col-md-12"><span>Hypothèses</span></h2>
  <ul class="icons-list">
    {% for hyp in calc.hypothesis %}
      <li><i class="fa fa-info-circle"></i>{{ hyp }}</li>
    {% endfor %}
  </ul>

  </br>
  {% include "calculation_image.html" with calc=calc category="hypothesis" %}
{% endif %}


{# ------------------------ #}
{# Informations principales #}
{# ------------------------ #}

<div hidden>
<h2 class="classic-title col-md-12"><span>Informations principales</span></h2>
    {{ calc_form.name }}
</div>
{# ---------------- #}
{# Choix du solveur #}
{# ---------------- #}
<div hidden>
<div class="form-group col-md-6">
  <span class="text-info">Choix du solveur</span>
  <div class="input-group has-feedback {% if calc_form.solver.errors %}has-error{% elif request.method == 'POST' %}has-success{% endif %}" id="id_solver_{{calc.name}}">
    <div class="input-group-addon">solveur</div>
    {{ calc_form.solver }}
  </div>
  {{ calc_form.solver.errors }}
</div>

</br>
{# --------------- #}
{# Choix du mesher #}
{# --------------- #}
{% if thereIsMesher %}
  <div class="form-group col-md-6">
    <span class="text-info">Choix du mailleur</span>
    <div class="input-group has-feedback {% if calc_form.mesher.errors %}has-error{% elif request.method == 'POST' %}has-success{% endif %}" id="id_mesher">
      <div class="input-group-addon">mailleur</div>
      {{ calc_form.mesher }}
    </div>
    {{ calc_form.mesher.errors }}
  </div>
  </br>
{% endif %}
</div>
{# ------------------------ #}
{# Affichage des parametres #}
{# ------------------------ #}
<h2 class="classic-title col-md-12"><span>Paramètres</span></h2>

{# ------------------------- #}
{# Paramètres dans un groupe #}
{# ------------------------- #}
{% for group, fields in groups.items %}
  {% if group != "ungrouped" %}
    <h3 class="classic-title col-md-12"><span>{{group}}</span></h3>
    {% include "calculation_image.html" with calc=calc category="group" group=group %}
    {% for field in fields %}
      {% include "calculation_field.html" with field=field %}
    {% endfor %}
  {% endif %}
{% endfor %}
</br>

{# ---------------------- #}
{# Paramètres sans groupe #}
{# ---------------------- #}
{% if groups.ungrouped %}
    <h2 class="classic-title col-md-12"><span>Paramètres divers</span></h2>
    {% include "calculation_image.html" with calc=calc category="parameters" %}
    {% for field in groups.ungrouped %}
        {% include "calculation_field.html" with field=field %}
    {% endfor %}
{% endif %}

source/calculation/templates/calculation_input_page.html
{% extends 'skeletons/min.html' %}
{% load utils %}
{% load staticfiles %}

{% block head %}
  {{ block.super }}
  <script type="text/javascript" src="{% static '/static/js/calculation.js' %}"></script>
{% endblock %}

{% block content %}
  <form method="POST" action="." >
  {% csrf_token %}
  {% include "calculation_input_content.html" with calc=calc calc_form=form groups=groups %}
  {# ------------- #}
  {# Submit button #}
  {# ------------- #}
  <div class="form-group col-md-12">
    <div class="col-sm-offset-1 col-md-12">
      <button type="submit" class="btn-system btn-large">Calculer</button>
    </div>
  </div>

  </form>
{% endblock %}

source/calculation/templates/calculation_result_page.html
{% extends 'skeletons/min.html' %}
{% load utils %}
{% load staticfiles %}


{% block content %}
  <h2 class="classic-title col-md-12"><span>Informations principales</span></h2>

  {# ------------- #}
  {# Nom du calcul #}
  {# ------------- #}
  <div class="form-group col-md-6">
    <span class="text-info">Nom du calcul</span>
    <div class="input-group">
      <div class="input-group-addon">name</div>
      <input class="form-control" type="text" value="{{resu.name}}" disabled="disabled" />
    </div>
  </div>
  </br>

  {# ---------------- #}
  {# Choix du solveur #}
  {# ---------------- #}
  <div class="form-group col-md-6">
    <span class="text-info">Choix du solveur</span>
    <div class="input-group">
      <div class="input-group-addon">solveur</div>
      <input class="form-control" type="text" value="{{resu.solver}}" disabled="disabled" />
    </div>
  </div>
  </br>

  {# --------------- #}
  {# Choix du mesher #}
  {# --------------- #}
  {% if thereIsMesher %}
    <div class="form-group col-md-6">
      <span class="text-info">Choix du mailleur</span>
      <div class="input-group">
        <div class="input-group-addon">mailleur</div>
        <input class="form-control" type="text" value="{{resu.mesher}}" disabled="disabled" />
      </div>
    </div>
    </br>
  {% endif %}

  <h2 class="classic-title col-md-12"><span>Caractéristiques du calcul</span></h2>
  <div class="form-group col-md-6">
    <span class="text-info">Temps CPU</span>
    <div class="input-group">
      <div class="input-group-addon">t<sub>CPU</sub></div>
      <input class="form-control" type="text" value="{{resu.cpu_time.total_seconds}}" disabled="disabled" />
      <div class="input-group-addon">secondes</div>
    </div>
  </div>
  </br>
  {# ------------------------------ #}
  {# Liste des paramètres résultats #}
  {# ------------------------------ #}
  <h2 class="classic-title col-md-12"><span>Résultats</span></h2>
  {% for field in form %}
    {% if 'ovar' in field.name %}
      {% include "calculation_field.html" with field=field %}
    {% endif %}
  {% endfor %}
  </br>

{% endblock %}